# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'True Pass' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks

  use_frameworks!
  pod 'Firebase/Core'
  pod 'FirebaseDatabase', '~> 4.0'
  pod 'FirebaseAuth'
  pod "QRCoder"
  pod "QRCodeReader"

  # Pods for CheckIn

end
